### ISSUE TITLE
Dataset request: <adequate access to infrastructure and facilities for people across Singapore>

### ISSUE THREAD

**Issue by ecinreb** [datagovsg/datagovsg-datasets#42] opened 2017-11-18 14:18 UTC
### Please provide the name of the dataset or describe the dataset that you're requesting:
1. number of elderly care facilities in Singapore, by sub zones
2. improved access to public transport 
3. number of senior corners in Singapore, by sub zones

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
------|---------|-------------
2017-09|Singapore|10000

sub zone, number, description
eg: Bedok, 346, elderly care centre
Tampines, 235, elderly care centre

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [X] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
I am working on a project in Murdoch Bachelor's degree program, and require this datasets for analysis.

**Comment by yongjun21** [comment] 2017-11-22 03:10
@ecinreb I believe the requirement of your assignment is to find datasets containing locations (lat, lon) of these facilities and bin them yourself into respective subzones with appropriate algorithms. There are many tools out there that can help you with this. An example will be http://turfjs.org/docs#booleanPointInPolygon. 

With so many different types of geospatial features (public toilets, bus stops, traffic crossings) and so many different ways of cutting up your map (planning areas, subzone, town council area), it is not reasonable to assume someone out there already have these aggregates prepared (number of public toilets by subzone, number of bus stops by planning area). I believe it is the intention of your lecturer for the students to figure out how to merge data from different sources so I apologize there's really little we can help on this.

**Comment by yongjun21** [comment] 2017-11-22 03:17
Closing as this is duplicate of issue #21 and #31

**Closed by yongjun21** 2017-11-22 03:17 UTC
