### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by navya0204** [datagovsg/datagovsg-datasets#30] opened 2017-11-02 08:14 UTC
### Please provide the name of the dataset or describe the dataset that you're requesting:
public transportation facilities in each area of singapore for senior citizens

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

month | country | passengers
--planningarea---|---subzone------|-----public transport facilities--------
2017-09|Singapore|10000

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [. ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
need this data to do a project on Which Planning Areas currently have the highest proportion of senior citizens served by public transport

**Comment by iewil** [comment] 2017-11-08 08:38
@navya0204 this is a duplicate of issue #31. closing issue

**Closed by iewil** 2017-11-08 08:38 UTC
