### ISSUE TITLE
Dataset request: Nutrition Info of Food in Singapore

### ISSUE THREAD

**Issue by maochawen** [datagovsg/datagovsg-datasets#401] opened 2019-04-05 13:05 UTC
### Please provide the name of the dataset or describe the dataset that you're requesting:
Nutrition Info of Food in Singapore, such as the food nutrition information available in the Healthy365 application

### Do you know which agency provides/can provide this data?

Health Promotion Board

### Please provide the fields expected in this dataset:

Food | Calorie 
------|---------
Chicken rice|300

### How frequently would you need this dataset to be updated?

- [ ] Annually
- [X ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [ ] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
We are a group of students who are trying to create an application to promote healthy living. This dataset will help users to track the amount of calories for the food they consume (with common food in Singapore)

**Comment by lennardl** [comment] 2019-04-08 00:54
Duplicate of #398

**Closed by lennardl** 2019-04-08 00:54 UTC
